package util

import (
	"fmt"
	"github.com/bwmarrin/snowflake"
)

// GetSnowflakeID return an ID generated by snowflake algorithm.
func GetSnowflakeID(nodeID int64) snowflake.ID {
	node, err := snowflake.NewNode(nodeID)
	if err != nil {
		fmt.Println("Err: ", err)
	}
	id := node.Generate()
	return id
}
